name: Build and Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code branch
        uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Leiningen
        run: |
          curl -o lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/
          lein --version

      - name: Build static site with Cryogen
        run: lein run

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: resources/public
          single-commit: false
